import { Inter } from "next/font/google";
import "./globals.css";
import  Header  from "./components/Header";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#2f2f2f]`}>
        <Header />
        {children}
        </body>
    </html>
  );
}
